# Generated by Django 4.2.14 on 2024-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_remove_course_credits_remove_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='year_of_study',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
    ]
