# Generated by Django 4.2.14 on 2024-08-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_questionpaper_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='intake',
            field=models.CharField(choices=[('JAN', 'JAN'), ('MAY', 'MAY'), ('AUG', 'AUG')], default='JAN', max_length=10),
        ),
    ]
