# Generated by Django 4.2.14 on 2024-08-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_faculty_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
