# Generated by Django 4.2.14 on 2024-08-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='questionnaire.department'),
        ),
    ]
